### ISSUE TITLE
[FEATURE] Force.com component type(s) not supported by plugin version 33 and 34 beta

### ISSUE THREAD

**Issue by chulai** [forcedotcom/idecore#135]
Good morning,

I'm having issues trying to download all the medatata with the **Force.com plugin versions 33 and 34 beta**. This is the error I get:

*The following component type(s) are not supported, so no component will be added to the package manifest editor for these types.*

![force com component types not supported](https://cloud.githubusercontent.com/assets/837749/9361673/f5b1406e-4672-11e5-8a80-979a8c5879d2.PNG)

I have tried with **both Force.com plugin versions** and **all Eclipse versions from 4.2 to 4.5** and with **Java 7 and Java 8**. Both Eclipse and Java were always 64-bit. 
Also I've tried from a **corporate network and a home network to not avail**.
Finally, I run my **tests against 3 Developer Pro sandboxes and 1 free Developer Edition all running Summer '15 (API version 34)**. I invariably got the same error.

This is the content of my \.metadata\.log file:

```
!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.591
!MESSAGE  WARN [2015-08-19 13:01:41,585] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'ActionLinkGroupTemplate': Unable to get bean for id 'ActionLinkGroupTemplate'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.618
!MESSAGE  WARN [2015-08-19 13:01:41,616] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'AuraDefinitionBundle': Unable to get bean for id 'AuraDefinitionBundle'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.621
!MESSAGE  WARN [2015-08-19 13:01:41,620] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'ChannelLayout': Unable to get bean for id 'ChannelLayout'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.625
!MESSAGE  WARN [2015-08-19 13:01:41,623] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'CorsWhitelistOrigin': Unable to get bean for id 'CorsWhitelistOrigin'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.642
!MESSAGE  WARN [2015-08-19 13:01:41,640] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'ExternalDataSource': Unable to get bean for id 'ExternalDataSource'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.649
!MESSAGE  WARN [2015-08-19 13:01:41,648] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'MatchingRule': Unable to get bean for id 'MatchingRule'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.652
!MESSAGE  WARN [2015-08-19 13:01:41,650] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'MatchingRules': Unable to get bean for id 'MatchingRules'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.655
!MESSAGE  WARN [2015-08-19 13:01:41,653] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'NamedCredential': Unable to get bean for id 'NamedCredential'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.667
!MESSAGE  WARN [2015-08-19 13:01:41,665] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'SharingCriteriaRule': Unable to get bean for id 'SharingCriteriaRule'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.671
!MESSAGE  WARN [2015-08-19 13:01:41,669] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'SharingOwnerRule': Unable to get bean for id 'SharingOwnerRule'


!ENTRY com.salesforce.ide.core 2 0 2015-08-19 13:01:41.673
!MESSAGE  WARN [2015-08-19 13:01:41,672] (ComponentFactory.java:getComponentBean:1154) - Unable to get component for id 'SharingRules': Unable to get bean for id 'SharingRules'


!ENTRY org.eclipse.jface 2 0 2015-08-19 13:01:41.777
!MESSAGE Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
!STACK 0
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:760)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:527)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1507)
	at org.eclipse.ui.dialogs.FilteredTree$2.runInUIThread(FilteredTree.java:523)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:330)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:360)
	at org.eclipse.jface.dialogs.MessageDialog.openWarning(MessageDialog.java:469)
	at com.salesforce.ide.core.internal.utils.Utils.openWarn(Utils.java:355)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestController.logAndDisplayWarnMsgIfNeeded(PackageManifestController.java:739)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestController.createModel(PackageManifestController.java:860)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestController.updateManifest(PackageManifestController.java:174)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestController.getEnabledCompTypeTreeNodes(PackageManifestController.java:433)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestTree$ManifestContentProvider.getElements(PackageManifestTree.java:689)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:1000)
	at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:700)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1349)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:353)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:906)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:617)
	at org.eclipse.jface.viewers.AbstractTreeViewer$1.run(AbstractTreeViewer.java:815)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:791)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:762)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1541)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:790)
	at org.eclipse.jface.viewers.AbstractTreeViewer$5.run(AbstractTreeViewer.java:1525)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1462)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:366)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1423)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:409)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestTree$PackageManifestTreeViewer.preservingSelection(PackageManifestTree.java:419)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1517)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:292)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1701)
	at com.salesforce.ide.ui.packagemanifest.PackageManifestTree.updateTree(PackageManifestTree.java:1683)
	at com.salesforce.ide.ui.wizards.project.ProjectCustomComponentsComposite.initialize(ProjectCustomComponentsComposite.java:116)
	at com.salesforce.ide.ui.wizards.project.ProjectCustomComponentsComposite.<init>(ProjectCustomComponentsComposite.java:73)
	at com.salesforce.ide.ui.wizards.project.ProjectCustomComponentsDialog.createDialogArea(ProjectCustomComponentsDialog.java:64)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:768)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
	at com.salesforce.ide.ui.wizards.project.ProjectCustomComponentsDialog.create(ProjectCustomComponentsDialog.java:162)
	at org.eclipse.jface.window.Window.open(Window.java:792)
	at com.salesforce.ide.ui.wizards.project.ProjectProjectContentComposite$8.widgetDefaultSelected(ProjectProjectContentComposite.java:294)
	at com.salesforce.ide.ui.wizards.project.ProjectProjectContentComposite$8.widgetSelected(ProjectProjectContentComposite.java:309)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at com.salesforce.ide.ui.actions.OpenProjectContentPropertiesAction.execute(OpenProjectContentPropertiesAction.java:38)
	at com.salesforce.ide.ui.actions.BaseAction.run(BaseAction.java:206)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

force-ide.log file shows identical errors.

I found people getting similar errors but I couldn't resolve the issue. I am inclined to think ~~this is a bug~~ (it is not, instead is missing functionality) in the Force.com plugin. I don't have this issue with the version 31 of the plugin. Well, actually I DID but only with the 'ExternalDataSource' metadata type that I've been ignoring since always.

Any idea?

Regards

**Comment by vazexqi** [comment]
@chulai  - It's not a bug. The dialog is telling you that we don't support those components. In general, we will focus more on programmatic types (Apex, VF) instead of Metadata types and we are not going to add support for all Metadata types.

If you could elaborate more I can provide more details on workarounds. It seems from your description that you would like to download all the metadata types? In that case, maybe the [Ant Migration tool](https://developer.salesforce.com/page/Force.com_Migration_Tool) is more suited for your needs.

**Comment by chulai** [comment]
@vazexqi Yes, that's my intention. For me, it was/is easier to use the Force.com plugin to download all metadata because it generates for you the package.xml file. 
Now, I understand you don't plan to add support for new metadata types in the plugin. So I will have to manually create an ANT script and package.xml file to do so. Will still be able to deploy new metadata files with the Force.com plugin or I will have to also use an ANT script for that?

Regards,
Chulai

**Comment by chulai** [comment]
My questions are three:
1) Can I still add the unsupported metadata types (unsupported by the Add/Remove Metadata components... dialog, I suppose) by hand in the package.xml file and then right-click my project and select Force.com > Refresh from server?
2) Can I still use the Force.com > Deploy to Server... option in these unsupported metatada types?
3) And what about Force.com > Save to Server option?

Otherwise, I would have to use ANT migration tool for the most common use cases or find another Salesforce IDE.

Thanks,
Chulai

**Comment by vazexqi** [comment]
@chulai 

1) Yes that could work but your mileage may vary depending on the particular type that you are trying to add. For instance, something more complicate that requires a different structure (top-level folder and file) would not work. What are you trying to add?
2) Same as 1 above
3) This is unlikely to work since the save to server would need to be able to determine what type it is. And since we don't have a specific type to support it, it is likely to fail.

What are the metadata types that you need? I'm trying to get a sense of what people actually use.

But, in general, the Force.com IDE is *not* going to be a point-n-click UI for just retrieving/deploying metadata types. If that's your use case, the ANT migration tool is definitely going to be a better route.

**Comment by chulai** [comment]
I don't have a particular metadata type I want to download but I want to download everything (or as much as possible). I use the IDE to get snapshots of the sandbox and store the history in a Git repository, but mainly as a mean to migrate changes between sandboxes. I haven't had good results with Change Sets for big changes and they have also several limitations: standard fields and objects cannot be moved,  sandboxes need to be related (created from the same prodution Org) and so on. Reproducing changes between sandboxes by hand (via the UI) is a very time consuming task so I tend to rely on the IDE to do that for almost but the basic change.

I've been able to deploy the following metadata types with the IDE:

* Authentication Provider.
* Call Center.
* Custom Console Component.
* Custom Permission.
* Data Category Group (SFDC recommends to do this manually because otherwise it removes from target Org any category not listed in the xml file being deployed).
* Entitlement Template.
* Flexible Page.
* Flow.
* Approval Post Template (Chatter).
* Scontrol Component.
* Sharing Set.
* Role.
* Settings (Misc.).
* Public Group (Adding Members is not supported by mdAPI and must be setup by UI).
* Document.
* Queue.
* Weblink (Custom Object) / Button or Link (Home).
* Sobject (& Custom Settings)	(“Grant Access Using Hierarchies” setting is not supported by mdAPI and must be setup by UI).
* Custom Label.
* Static Resource File.
* Apex Class.
* Apex Component.
* Apex Page.
* Page Layout.
* Apex Trigger.
* Custom Tab.
* Custom/Standard Application.
* Custom Report Type.
* Translation.
* Force.com App/Salesforce1 Nav Menu.
* Custom Object Translation.
* Letterhead (Email).
* Email Template.
* Workflow Rule.
* Approval Process.
* Custom Report.
* Account Sharing Rule.
* Case Assignment Rule.
* Campaign Sharing Rule.
* Case Sharing Rule.
* Contact Sharing Rule.
* Lead Sharing Rule.
* Opportunity Sharing Rule.
* User Sharing Rule.
* Home Page Component.
* Home Page Layout.
* Remote Site Setting.
* Custom Object Sharing Rule.
* Connected App Configuration (“consumerKey” and “consumerSecret” settings are not supported by mdAPI version <= 31 and must be setup by UI. Remove them from the xml).
* Dashboard.
* Milestone (Entitlement Process).
* Entitlement Process.
* Auto-response Rule (email).
* Chatter Answers & Ideas Zones.
* Create/Update Action (Chatter Publisher).
* SAML Single Sign-On (Certificates and Endpoints settings are not supported by mdAPI and must be setup by UI).
* Profile.
* Permission Set (Assignment of Permission Sets to Users is not supported by mdAPI and must be setup with the Data Loader).

While many other metadata I decided to reproduce it manually via the Setup in the UI:	
* Community.
* Site.
* Force.com Site.
* Setup > Company Profile > Company Information: Multicurrency, Default Locale, Default Language, etc.
* Setup > Security Controls > Sharing Settings > External Sharing Model.
* Setup > Security Controls > Login Access Policies.
* Setup > Translation Workbench > Translation Settings.
* Setup > Administer > Email Administration > Deliverability.
* Setup > Administer > Domain Management > My Domain.
* Setup > Build > Customize > User Interface.
* Object History Tracking.
* Chatter Settings.
* Build > Customize > Social Apps Integration > Social Accounts and Contacts > Settings.
* And many many other settings.

So the idea behind my original request is that I want to use the mdAPI as much as possible so not to rely on manual changes.

**Comment by umapen** [comment]
I am having exact same problem. Is there any workaround to get these components downloaded to eclipse?

**Comment by marcuscorner** [comment]
I find myself in a similar position.
Our team used to use Eclipse for a number of tasks, which we've gradually moved away from, in favour of simply using the Dev Console.

However, what we have found very useful, is using the IDE to generate specific components in the package.xml.  I believe that this is a very common practice, so it's very dissapointing to learn that not all components will be supported.

**Comment by vazexqi** [comment]
@marcuscorner  - I'm asking to determine the actual use case. Do you edit those files in the IDE? Or do you just want a convenient point-and-click way of retrieving them (or, as you mentioned, to generate the package.xml for you?)

**Comment by marcuscorner** [comment]
It's a little bit of both @vazexqi 

Primarily though, we use the IDE to point-and-click select components (in component types where we need explicit control) in order to generate the package.xml.  Once we've created the package.xml we then move to the Ant Migration Tool, to retrieve/deploy as appropriate.

**Comment by danielsokolowski** [comment]
Is there ever going to be support for `AuraDefinitionBundle` ?

**Comment by gwestersfdc** [comment]
@danielsokolowski AuraDefinitionBundle will be supported in conjunction with Lightning Component creation in the IDE. It's in design right now and hasn't been tagged for a particular release, but it will happen this year.

**Comment by danielsokolowski** [comment]
Glorious, I will ping the team with the news.

On 1/26/2016 10:28 AM, Greg Wester wrote:
>
> @danielsokolowski <https://github.com/danielsokolowski> 
> AuraDefinitionBundle will be supported in conjunction with Lightning 
> Component creation in the IDE. It's in design right now and hasn't 
> been tagged for a particular release, but it will happen this year.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/forcedotcom/idecore/issues/135#issuecomment-175077970>.
>

-- 
Daniel Sokolowski
http://danielsokolowski.com/
Office: 613-817-6833
Kingston, ON K7L 1H3, Canada


Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed
and may contain confidential and/or privileged material. Any review re-transmission dissemination
or other use of or taking of any action in reliance upon this information by persons or entities
other than the intended recipient is prohibited. If you received this in error please contact
the sender immediately by return electronic transmission and then immediately delete this
transmission including all attachments without copying distributing or disclosing same.

**Comment by vazexqi** [comment]
AuraDefinitionBundle is coming but it's unlikely we are going to support the other types in particular if the use case is more of point-and-click to generate a package.xml to do retrieve/deploy. The point-and-click feature should be done in a separate tool that could be embedded into the IDE.

**Comment by aaronking574** [comment]
Will I be able to get the global picklist and global picklist value files?
