### ISSUE TITLE
Force.com IDE v38.0 can't run unit test

### ISSUE THREAD

**Issue by doudourush** [forcedotcom/idecore#220]
### Summary
I don't know if anyone has experienced this, I just updated force.com IDE to v38.0 (I used to use a very old version, v28 maybe). My problem is that when I tried to run a unit test, no test class/method is loaded in the "run configuration" dialog.

### Steps To Reproduce:
1. Right click on the project->Run As->run configurations
2. Right click on "Apex Test", and create a new test
3. In project tab, select a project
4. Switch tab to Test

### Expected result
I assume you can select the test classes/methods to run by clicking the "Search" button.

### Actual result
The search buttons are grayed out and not clickable.
![capture2](https://cloud.githubusercontent.com/assets/8181899/24709133/f13b4e0a-19e6-11e7-9435-f11a6efd7e93.PNG)

### Additional information

Also, when I checked the box "use suites" and then unchecked it, the Search button is available but when I click on it, there's no test class loaded to select
![capture3](https://cloud.githubusercontent.com/assets/8181899/24709289/6ae5073c-19e7-11e7-98fd-ca87e309cfc3.PNG)
Sometimes, there's an error pops up(somethimes doesn't)
![capture](https://cloud.githubusercontent.com/assets/8181899/24709327/8441f870-19e7-11e7-9dca-9840e7adbe45.PNG)
by checking the log, there's more info about the error
 `ERROR [2017-04-04 14:05:30,944] (RunTestsView.java:enqueueTests:357) - Failed to enqueue tests. Tests array: 
ERROR [2017-04-04 14:05:32,617] (RunTestsView.java:runTests:263) - Unexpected error
java.lang.NullPointerException
at com.salesforce.ide.apex.internal.core.ApexSourceUtils.lambda$1(ApexSourceUtils.java:302)
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.collect(Unknown Source)
at com.salesforce.ide.apex.internal.core.ApexSourceUtils.filterSourcesByType(ApexSourceUtils.java:303)
at com.salesforce.ide.apex.internal.core.ApexSourceUtils.filterSourcesByClass(ApexSourceUtils.java:252)
at com.salesforce.ide.apex.internal.core.ApexSourceUtils.findTestClassesInProject(ApexSourceUtils.java:70)
at com.salesforce.ide.ui.views.runtest.RunTestsView.findTestClasses(RunTestsView.java:894)
at com.salesforce.ide.ui.views.runtest.RunTestsView.runTests(RunTestsView.java:232)
at com.salesforce.ide.ui.views.runtest.RunTestsLaunchConfigurationDelegate.launch(RunTestsLaunchConfigurationDelegate.java:124)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Eclipse version**: Neon.3 Release(4.6.3)

**Force.com IDE version**: v38.0

**OS and version**: Windows 7

**Java version**: version 8 update 121

**Comment by debflores** [comment]
I'm having the same issue.  In addition, when I attempt to create a test suite, I receive the following error, even though I have properly-annotated test classes in the org:

![image](https://cloud.githubusercontent.com/assets/8963805/25618805/6db92986-2f16-11e7-9934-e02a33d98b74.png)

**Comment by richardwangapex** [comment]
hi, I got the same issue. Have you guys found the solution? Thanks! Rich

**Comment by funmark** [comment]
Hi, Similar issue here:

` WARN [2018-08-03 16:41:08,195] (HTTPAdapter.java:unmarshallResponse:107) - 403: Forbidden from https://na53.salesforce.com/services/data/v38.0/tooling/runTestsSynchronous/ with error: [{"message":"Your classId and className properties are missing or null. Provide the ID or name of an Apex class that has test methods, and use this format: \"classId\" : \"<classId>\" or \"className\" : \"<className>\"","errorCode":"INVALID_INPUT"}]
ERROR [2018-08-03 16:41:08,196] (RunTestsView.java:enqueueTests:357) - Failed to enqueue tests. Tests array: {"tests":[{"testMethods":["test_addHelloWorld"]}],"testLevel":"RunSpecifiedTests","totalTests":1,"specificTests":true}
 WARN [2018-08-03 16:48:48,189] (DefaultBuilder.java:applyDirtyMarkers:93) - TODO: apply 'Save locally only...' markers on each resource
`

Any fixes/workarounds ?
thanks

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
