### ISSUE TITLE
New Jorje Parser fails to parse valid Apex code in PMD integration

### ISSUE THREAD

**Issue by up2go-rsoesemann** [forcedotcom/idecore#227]
I am Robert the maintainer of the PMD Apex module. Internally we use your Jorje Parser.

Since a year ago, the Salesforce IDE uses a new version of the jorje compiler jars, see commit https://github.com/forcedotcom/idecore/tree/3083815933c2d015d03417986f57bd25786d58ce/com.salesforce.ide.apex.core/lib

I tried to update the PMD integration. After adjusting to the API changes (e.g. new/renamed/deleted AST node types), I'm running into some problems:

The new compiler seem to have a bug when parsing the following Apex snippet, which contains SOQL:

```
public class Foo {
public List<SObject> test1() {
       return Database.query("Select Id from Account LIMIT 100");
    }
}
```

The stacktrace is this:

java.lang.NullPointerException
	at apex.jorje.semantic.ast.AstNodeFactory.createExpressions(AstNodeFactory.java:443)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.<init>(MethodCallExpression.java:95)
	at apex.jorje.semantic.ast.AstNodeFactory$2._case(AstNodeFactory.java:249)
	at apex.jorje.semantic.ast.AstNodeFactory$2._case(AstNodeFactory.java:186)
	at apex.jorje.data.ast.Expr$MethodCallExpr.match(Expr.java:1275)
	at apex.jorje.semantic.ast.AstNodeFactory.create(AstNodeFactory.java:185)
	at apex.jorje.semantic.ast.statement.ReturnStatement.lambda$new$0(ReturnStatement.java:50)
	at java.util.Optional.map(Optional.java:215)
	at apex.jorje.semantic.ast.statement.ReturnStatement.<init>(ReturnStatement.java:50)
	at apex.jorje.semantic.ast.AstNodeFactory$1._case(AstNodeFactory.java:77)
	at apex.jorje.semantic.ast.AstNodeFactory$1._case(AstNodeFactory.java:60)
	at apex.jorje.data.ast.Stmnt$ReturnStmnt.match(Stmnt.java:546)
	at apex.jorje.semantic.ast.AstNodeFactory.create(AstNodeFactory.java:59)
	at apex.jorje.semantic.ast.AstNodeFactory.lambda$createStatements$2(AstNodeFactory.java:450)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at apex.jorje.semantic.ast.AstNodeFactory.createStatements(AstNodeFactory.java:451)
	at apex.jorje.semantic.ast.statement.BlockStatement$Builder$1._case(BlockStatement.java:266)
	at apex.jorje.semantic.ast.statement.BlockStatement$Builder$1._case(BlockStatement.java:263)
	at apex.jorje.data.ast.Stmnt$BlockStmnt.match(Stmnt.java:418)
	at apex.jorje.semantic.ast.statement.BlockStatement$Builder.lambda$setStmnt$1(BlockStatement.java:262)
	at apex.jorje.semantic.ast.statement.BlockStatement.<init>(BlockStatement.java:69)
	at apex.jorje.semantic.ast.statement.BlockStatement.<init>(BlockStatement.java:48)
	at apex.jorje.semantic.ast.statement.BlockStatement$Builder.build(BlockStatement.java:292)
	at apex.jorje.semantic.ast.AstNodeFactory$1._case(AstNodeFactory.java:67)
	at apex.jorje.semantic.ast.AstNodeFactory$1._case(AstNodeFactory.java:60)
	at apex.jorje.data.ast.Stmnt$BlockStmnt.match(Stmnt.java:418)
	at apex.jorje.semantic.ast.AstNodeFactory.create(AstNodeFactory.java:59)
	at apex.jorje.semantic.ast.member.MethodFactory.lambda$createUserMethod$0(MethodFactory.java:71)
	at java.util.Optional.map(Optional.java:215)
	at apex.jorje.semantic.ast.member.MethodFactory.createUserMethod(MethodFactory.java:71)
	at apex.jorje.semantic.ast.member.MethodFactory.createUserMethod(MethodFactory.java:51)
	at apex.jorje.semantic.ast.compilation.UserClassMembers$Builder._case(UserClassMembers.java:308)
	at apex.jorje.data.ast.BlockMember$MethodMember._switch(BlockMember.java:374)
	at apex.jorje.semantic.ast.compilation.UserClassMembers.create(UserClassMembers.java:191)
	at apex.jorje.semantic.ast.compilation.UserClass.<init>(UserClass.java:88)
	at apex.jorje.semantic.ast.AstNodeFactory$3._case(AstNodeFactory.java:392)
	at apex.jorje.semantic.ast.AstNodeFactory$3._case(AstNodeFactory.java:374)
	at apex.jorje.data.ast.CompilationUnit$ClassDeclUnit.match(CompilationUnit.java:371)
	at apex.jorje.semantic.ast.AstNodeFactory.create(AstNodeFactory.java:373)
	at apex.jorje.semantic.compiler.CodeUnit.parse(CodeUnit.java:85)
	at apex.jorje.semantic.compiler.CompilerStage$1.invoke(CompilerStage.java:38)
	at apex.jorje.semantic.compiler.ApexCompiler.processNext(ApexCompiler.java:164)
	at apex.jorje.semantic.compiler.ApexCompiler.compileInternal(ApexCompiler.java:98)
	at apex.jorje.semantic.compiler.ApexCompiler.compile(ApexCompiler.java:86)
	at net.sourceforge.pmd.lang.apex.ast.CompilerService.compile(CompilerService.java:93)
	at net.sourceforge.pmd.lang.apex.ast.CompilerService.visitAstsFromStrings(CompilerService.java:87)
	at net.sourceforge.pmd.lang.apex.ast.CompilerService.visitAstFromString(CompilerService.java:75)
	at net.sourceforge.pmd.lang.apex.ast.ApexParser.parseApex(ApexParser.java:42)
	at net.sourceforge.pmd.lang.apex.ast.ApexParser.parse(ApexParser.java:51)
	at net.sourceforge.pmd.lang.apex.ast.ApexCompilerSoqlTest.testSoqlCompilation(ApexCompilerSoqlTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by vazexqi** [comment]
@up2go-rsoesemann  - There are at least two things that wrong with the syntax of your example.

### Before

```
public class Foo {
public List test1() { // Needs the generic type for the list
return Database.query("Select Id from Account LIMIT 100"); // Needs to use ' instead of "
}
}
```

### Fixed

```
public class Foo {
    public List<Account> test1() {
    return Database.query('Select Id from Account LIMIT 100');
    }
}
```

If you make those changes do you get the expected results?

**Comment by up2go-rsoesemann** [comment]
I was copy & pasting the code from the issue in PMD (https://github.com/pmd/pmd/pull/489) and this seem to have messed the code. Indeed the error happens when parsing the second valid code.

**Comment by vazexqi** [comment]
@up2go-rsoesemann 

I'm not sure the snippet you sent me is correct. You are still using " (double quotes) instead of ' (single quotes).

**Comment by adangel** [comment]
@vazexqi Thanks for your help. With single quotes, it works indeed!
I think, we can close this issue then.
